docker-build-master:
  # Official docker image.
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - git submodule init
    - git submodule update
    - ./buildall
    - ./pushall2docker
  only:
    - master
