docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - umask 0022
    - apk add git
    - apk add bash
    - apk add curl
    - git submodule init
    - git submodule update
    - chmod -R og-w .
    - ./buildall
    - ./pushall2docker
    - "curl -X POST -F token=$CI_DOCKER_NNCP_TRIGGER -F ref=main https://salsa.debian.org/api/v4/projects/67697/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_APACHE_PROXY_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67698/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_TOR_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67701/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_AMPACHE_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67750/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_WEEWX_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67751/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_UUCP_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67766/trigger/pipeline"
    - "curl -X POST -F token=$CI_DOCKER_MYTHTV_TRIGGER -F ref=master https://salsa.debian.org/api/v4/projects/67769/trigger/pipeline"

 
  only:
    - master
