docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - apk add git
    - apk add bash
    - apk add curl
    - git submodule init
    - git submodule update
    - ./buildall
    - ./pushall2docker
    - "curl -X POST -F token=$CI_DOCKER_NNCP_TRIGGER -F ref=main https://salsa.debian.org/api/v4/projects/67697/trigger/pipeline"
  only:
    - master
