#!/bin/bash
set -e
set -x

buildbranch() {
        for DIR in debian-base-{minimal,standard,security,vnc,apache,apache-php}; do
                cd $DIR
                git checkout $1
                docker build -t jgoerzen/$DIR:$2 .
                cd ..
        done
}

buildbranch master latest
#buildbranch jessie jessie
#git checkout master

