#!/bin/bash
set -e
set -x

buildbranch() {
        git checkout $1
        for DIR in debian-base-{minimal,standard,security,apache,apache-php}; do
                cd $DIR
                docker build -t jgoerzen/$DIR:$2 .
                cd ..
        done
}

buildbranch master latest
buildbranch jessie jessie
git checkout master

