#!/bin/bash

set -e
for SUBDIR in debian-base-*; do
  cp README.perimage.md "$SUBDIR/README.md"
done

git submodule foreach "git commit -m 'Update README.md from docker-debian-base/README.perimage.md' README.md"
