#!/bin/bash
set -e
set -x

buildbranch() {
        for DIR in debian-base-{minimal,standard,security,vnc,apache,apache-php}; do
                cd $DIR
                git checkout $1
                docker push jgoerzen/$DIR:$2
                docker push jgoerzen/$DIR:$3
                cd ..
        done
}

buildbranch bullseye
#buildbranch jessie jessie
#git checkout master

