#!/bin/bash
set -e

if [ "$DEBBASE_SYSLOG" = "internal" ]; then
        echo "Using internal syslog (config file /etc/syslog.conf.internal)"
        echo "Your log files will be in /var/log"
        ln -sf syslog.conf.internal /etc/syslog.conf
else
        echo "Sending syslog to Docker (config file /etc/syslog.conf.stdout)"
        ln -sf syslog.conf.stdout /etc/syslog.conf
fi

