#!/bin/bash

set -e

echo "JESSIE IS NO LONGER SUPPORTED AT DEBIAN; USING ARCHIVE SITE"

set -x

sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
sed -i '/jessie-updates/d' /etc/apt/sources.list

# The valid-until in the archive backports InRelease is no longer being updated.
echo 'Acquire::Check-Valid-Until "0";' > /etc/apt/apt.conf.d/10no-check-valid-until-debian-base-jessie
