#!/bin/bash

set -e
set -x

FILESDIR="/usr/local/debian-base-setup/files"
COPY () {
    cp -a "$FILESDIR/$1" "$2"
}

# Copy files into place

COPY syslog.conf /etc/syslog.conf.stdout

apt-get update
apt-get -y --no-install-recommends install inetutils-syslogd cron anacron at logrotate systemd-sysv initscripts
apt-get -y --no-install-recommends install psmisc procps
apt-get -y -u dist-upgrade
apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

dpkg-divert --local --divert /etc/syslog.conf.internal --rename /etc/syslog.conf

/usr/local/bin/docker-wipelogs

# Let daemons start
mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled
