#!/bin/bash
set -e

# We can't kill init, but we can make it re-exec itself (/bin/true)
ln -sf /bin/true /sbin/init
# Since telinit is linked to /sbin/init, we have to call init.real instead
# of telinit here.
echo "Container exiting; stopping init."
/sbin/init.real U

