#!/bin/bash
set -e

if [ -d /etc/ssh -a -f /etc/ssh/sshd_config -a ! -f /etc/ssh/ssh_host_rsa_key ]; then
        echo "Generating SSH host keys..."
        dpkg-reconfigure openssh-server || true
fi

