#!/bin/bash

set -e
run-parts --verbose /usr/local/preinit

echo "Starting systemd"

# container=docker per https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
# and https://serverfault.com/a/915878
export container=docker

#exec strace -s 200 -o /tmp/foo -f /bin/systemd --system --default-standard-output=tty --default-standard-error=tty --log-target=console --log-level=debug 100>&1 1>&-
exec /bin/systemd --system 100>&1 1>&-

