#!/bin/bash

set -e
set -x
echo "Cleaning up; ignore errors here:"
/etc/init.d/checkroot-bootclean.sh || true
rm -f /tmp/.clean || true
if [ "$DEBBASE_SYSLOG" = "internal" ]; then
        ln -sf syslog.conf.internal /etc/syslog.conf
else
        ln -sf syslog.conf.stdout /etc/syslog.conf
fi
echo "Starting sysvinit"
exec /sbin/init 100>&1 1>&-

